
/* eslint-disable prettier/prettier */
export default {
    screens: {
        navigators: {
            authNavigator: 'authNavigator',
            bottomTabNavigator: 'bottomTabNavigator',
            userbottomTabNavigator: 'userbottomTabNavigator',
            bmNavigator:'BMNavigator',
            patientNavigator:'PatientNavigator'
            
          },

        authNavigator: {
            login: 'login',
            bmlogin:'bmlogin',
            userlogin:'userlogin',
            otp:'OTP Verification',
            register: 'Register',

        },
        tabNavigator: {
          homescreen: 'Home',
          create_camp:'Create Camp',
          profile:'Profile',
          
      },
      patienttabNavigator: {
        patienthome:'Home',
        diary:"Diary",
        profile:'Profile',
       
    },
      
        api_names: {
            user_login:'api/login',
            forgetpassword:'api/forgetPassword',
            create_camp:'api/create_camp',
            camp_list:'api/camp_list',
            completed_camp_list:'api/completed_camp_list?creator_id=',
            // doctor_list:'api/doctors',
            doctor_list:'api/doctor_list_by_emp_code?emp_code=',
            create_patient:'api/create_patient',
            capture_start_image:'api/capture_image',
            capture_end_image:'api/capture_image/update',
            setting:'api/settings',
            profiledetails:'api/bm_user_profile',
            updateprofile:'api/update_bm_user_profile',
            add_patient:'api/create_patient',
            patient_list:'api/patients?camp_id=',
            update_camp:'api/update/camp',
            search:'api/patients/search?camp_id=',


            patient_login:'api/send_otp',
            verify_otp:'api/verify_otp',
            user_setting:'api/settings',
            patient_profile:'api/patient_profile',
            update_patient_profile:'api/update_patient_profile',
            add_body_measurement:'api/add_body_measurement',
            body_measurements_list:'api/list_body_measurements?patient_id=',
            add_weight:'api/add_weight_management',
            weight_list:'api/list_weight_managements?patient_id=',
            update_weight:'api/update_weight_management',
            update_body_details:'api/update_body_measurement',
            weight_metrics:'api/calculate_weight_metrics',
            add_snack:'api/add_snack',
            snack_list:'api/list_snacks?patient_id=',
            exercise:'api/exercise_list',
            days:'api/days',
            step_list:'api/steps?patient_id=',
            update_status:'api/update_step_status',
            veg_days_list:'api/diet_list?patient_id=',
            nonveg_days_list:'api/diet_list?patient_id=',
            diet_days_list:'api/diet_day',
            veg_dietPlan:'api/diet_plan?patient_id=',
            nonveg_dietPlan:'api/diet_plan?patient_id=',
            diet_status:'api/update_diet_status',
            monthly_exercise_list:'api/list_ExerciseCompletedInMonth?patient_id=${patient_id}&month=${month}&year=${year}',
            doctor_details:'api/doctor_details?id=',
            monthly_diet_list:'api/list_DietCompletedInMonth?patient_id=${patient_id}&month=${month}&year=${year}&type=${type}',
            share_camp:'api/camp'
          },

        appStrings: {
            splash:'PCOSLite',
            pcoslite:'Pcoslite',
            notes:'Nutritionists Notes',
            onboarding:'onboarding',
            networkErrorTitle: 'Network Error',
            networkErrorMsg: 'You are offline. Please check your internet connection.',
            appname:'PCOSLite',           
            camp:"Camp",
            campDetails:'Camp Details',
            addPatient:"Patient Form",
            patientDetails:'Patient Details',
            profile: 'Profile',
            userProfile:'Patient Profile',
            myProfile:'My Profile',
            contactUS:'Contact US',
            weightScreen:'Weight Management',
            addWeight:'Add Weight',
            updateweight:'Update Weight',
            updatebodydetails:'Update Body Details',
            dietPlan:'Diet Plan',
            vegDiet:'Veg Diet Plan',
            nonvegDiet:'Non Veg Diet Plan',
            exercise:'Exercise',
            exerciseStep:'ExerciseStep',
            bodydetails:"Body Details",
            addsnack:'Add Snack',
            calorie:'Calories Counter',
            viewProfile:'Profile Details',
            vegCalorie:'Calories',
            aboutUs:'About Us',
            about:'About us',
            terms:'Terms And Conditions',
            privacy_policy:'Privacy Policy',
            edit_camp:'Edit Camp',
            completed:'Completed Camp',
            rateus:'Rate US',
            share:'Share this App',
            my_basket:'Basket',
            my_orders:'My Orders',
            qr_code:'QR Code',
            terms_conditions:'Term and Conditions',
            refund:"Refund Policy",
            cancellation:"Cancellation Policy",
            mapAddress:"Add Address",
            deliveryNote:"Delivery Note",
           // privacy_policy:"Privacy Policy",
            logout:'Logout',
            logout_msg: "Are you sure want to logout?",
            no: "No",
            yes: "Yes",
            
            

    },
},

};
