export default {
  app_flow: 'app_flow',
  customer_id : 'customer_id',
  patient_id:'patient_id',
  access_token :'access_token',
  authorization_token :'authorization_token',
  data:'data',
  user_data: 'user_data',
  campId:'campId',
  name: 'name',
  email: 'email',
  image:'image',
  role:'role',
  emp_code:'emp_code',
  currentWeight:'currentWeight',
  goalWeight:'goalWeight',
  username:'username',
  userimage:'userimage',
  patient_data:'patient_data',
  bmiValue:'bmiValue',
  bmiCategory:'bmiCategory',
  timer:'timer',
  status:'status',
  selected:'selected'
};
